package devwright

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const sshHeader = "# Generated by devwright\n"
const sshInclude = `Include "~/.ssh/devwright/*.config"`

func sshConfig(state instance) string {
	if state.Backend == "incus" {
		return incusSSHConfig(state)
	}
	path := strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(filepath.Join(state.Dir, "ssh.config"))
	return fmt.Sprintf(`Host lima-%s
  IdentityAgent none
  ForwardAgent no
  ControlMaster auto
  ControlPath ~/.ssh/control-%%C
  ControlPersist 60
  Include "%s"

Host *
`, state.Name, path)
}

func optionalFile(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	return data, err
}

// atomicWrite replaces a file without following a final symlink or leaving a
// partially written SSH configuration if the process is interrupted.
func atomicWrite(path string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".devwright-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}

func (v *vm) installSSH(state instance) error {
	filename := state.Name + ".config"
	if state.Backend == "incus" {
		filename = state.Name + ".incus.config"
	}
	backend := "lima"
	if state.Backend == "incus" {
		backend = "incus"
	}
	return v.installSSHText(filename, sshConfig(state), fmt.Sprintf("SSH ready: ssh %s-%s (dev); ssh root@%s-%s (admin)", backend, state.Name, backend, state.Name))
}

func (v *vm) installSSHText(filename, content, message string) error {
	dir := filepath.Join(v.home, ".ssh", "devwright")
	target := filepath.Join(dir, filename)
	if info, err := os.Lstat(target); err == nil && !info.Mode().IsRegular() {
		return fmt.Errorf("refusing to overwrite non-regular SSH file: %s", target)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	old, err := optionalFile(target)
	if err != nil {
		return err
	}
	if old != nil && !strings.HasPrefix(string(old), sshHeader) {
		return fmt.Errorf("refusing to overwrite unmanaged SSH file: %s", target)
	}
	config := filepath.Join(v.home, ".ssh", "config")
	existing, err := optionalFile(config)
	if err != nil {
		return err
	}
	hasInclude := false
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSuffix(line, "\r") == sshInclude {
			hasInclude = true
		}
	}
	if !hasInclude {
		if info, err := os.Lstat(config); err == nil && !info.Mode().IsRegular() {
			return fmt.Errorf("SSH config is a symlink or non-regular file; add this include to its source: %s", sshInclude)
		} else if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	if !hasInclude && existing != nil {
		backup, err := os.CreateTemp(filepath.Dir(config), "config.before-devwright-*")
		if err != nil {
			return err
		}
		if _, err := backup.Write(existing); err != nil {
			backup.Close()
			return err
		}
		if err := backup.Close(); err != nil {
			return err
		}
	}
	if err := atomicWrite(target, []byte(sshHeader+content)); err != nil {
		return err
	}
	if !hasInclude {
		if err := atomicWrite(config, []byte(sshInclude+"\n\n"+string(existing))); err != nil {
			return err
		}
	}
	fmt.Fprintln(v.out, message)
	return nil
}
