package devwright

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (a *userAdmin) sshRulePath(name string) string {
	return filepath.Join(a.etc, "ssh", "sshd_config.d", "00-devwright-"+name+".conf")
}
func (a *userAdmin) keysPath(name string) string {
	return filepath.Join(a.etc, "ssh", "devwright", "devwright-"+name+".keys")
}
func (a *userAdmin) sshRule(s *userState) []byte {
	return []byte(fmt.Sprintf("# Generated by devwright for %s\nMatch User %s\n  AuthenticationMethods publickey\n  PubkeyAuthentication yes\n  PasswordAuthentication no\n  KbdInteractiveAuthentication no\n  AuthorizedKeysFile %s\n  AuthorizedKeysCommand none\n  AllowAgentForwarding no\n  X11Forwarding no\n  AllowTcpForwarding local\n  PermitUserRC no\nMatch all\n", s.Account, s.Account, a.keysPath(s.Name)))
}
func (a *userAdmin) sshEffective(account string) (map[string]string, error) {
	text, err := a.command(nil, "/usr/sbin/sshd", "-T", "-C", "user="+account+",host=localhost,addr=127.0.0.1")
	if err != nil {
		return nil, err
	}
	result := map[string]string{}
	for _, line := range strings.Split(text, "\n") {
		k, v, ok := strings.Cut(line, " ")
		if ok {
			result[k] = v
		}
	}
	return result, nil
}
func (a *userAdmin) checkSSHEffective(s *userState) error {
	effective, err := a.sshEffective(s.Account)
	if err != nil {
		return err
	}
	expected := map[string]string{"authenticationmethods": "publickey", "pubkeyauthentication": "yes", "passwordauthentication": "no", "kbdinteractiveauthentication": "no", "authorizedkeysfile": a.keysPath(s.Name), "authorizedkeyscommand": "none", "allowagentforwarding": "no", "x11forwarding": "no", "allowtcpforwarding": "local", "permituserrc": "no", "permituserenvironment": "no"}
	for key, want := range expected {
		if effective[key] != want {
			return fmt.Errorf("host SSH policy overrides required %s for %s (expected %q, got %q); adjust host policy administratively", key, s.Account, want, effective[key])
		}
	}
	return nil
}
func (a *userAdmin) installSSH(s *userState) error {
	p := a.sshRulePath(s.Name)
	before, err := optionalFile(p)
	if err != nil {
		return err
	}
	if before != nil && !bytes.HasPrefix(before, []byte("# Generated by devwright for "+s.Account+"\n")) {
		return errors.New("refusing unrelated SSH drop-in")
	}
	// Compare effective root settings as an unrelated account, in addition to the
	// exact Match scope. Never publish an invalid SSH config or leave it installed.
	rootBefore, err := a.sshEffective("root")
	if err != nil {
		return err
	}
	if err := writeUserFile(a.keysPath(s.Name), []byte(s.PublicKey+"\n"), 0644); err != nil {
		return err
	}
	wanted := a.sshRule(s)
	if err := writeUserFile(p, wanted, 0644); err != nil {
		return err
	}
	valid := false
	defer func() {
		if !valid {
			if before == nil {
				os.Remove(p)
			} else {
				_ = writeUserFile(p, before, 0644)
			}
		}
	}()
	if _, err := a.command(nil, "/usr/sbin/sshd", "-t"); err != nil {
		return err
	}
	if err := a.checkSSHEffective(s); err != nil {
		return err
	}
	rootAfter, err := a.sshEffective("root")
	if err != nil {
		return err
	}
	for k, v := range rootBefore {
		if rootAfter[k] != v {
			return fmt.Errorf("SSH drop-in unexpectedly changed unrelated account setting %s", k)
		}
	}
	if !bytes.Equal(before, wanted) {
		if err := a.reloadSSH(); err != nil {
			return err
		}
	}
	valid = true
	return nil
}
func (a *userAdmin) reloadSSH() error {
	if _, err := a.command(nil, "/usr/sbin/sshd", "-t"); err != nil {
		return err
	}
	if a.goos == "darwin" {
		return nil
	} // Remote Login launches sshd for each connection.
	for _, unit := range []string{"ssh.service", "sshd.service"} {
		if _, err := a.command(nil, "/usr/bin/systemctl", "is-active", "--quiet", unit); err == nil {
			_, err := a.command(nil, "/usr/bin/systemctl", "reload", unit)
			return err
		}
	}
	return errors.New("no active system ssh.service or sshd.service; enable the system SSH service administratively")
}
func (a *userAdmin) hostKeys() ([]string, error) {
	effective, err := a.sshEffective("root")
	if err != nil {
		return nil, err
	}
	_ = effective
	// Pin through the local administrative filesystem, never ssh-keyscan's
	// unauthenticated network response. Use the server's configured HostKey list.
	text, err := a.command(nil, "/usr/sbin/sshd", "-T")
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, line := range strings.Split(text, "\n") {
		if !strings.HasPrefix(line, "hostkey ") {
			continue
		}
		path := strings.TrimPrefix(line, "hostkey ")
		pub, err := a.command(nil, "/usr/bin/ssh-keygen", "-y", "-f", path)
		if err != nil {
			return nil, err
		}
		f := strings.Fields(pub)
		if len(f) < 2 {
			return nil, errors.New("invalid system SSH host key")
		}
		keys = append(keys, f[0]+" "+f[1])
	}
	if len(keys) == 0 {
		return nil, errors.New("no system SSH host keys")
	}
	return keys, nil
}
