#!/usr/bin/env python3
"""Manage only VMs created from this repository. Requires Python 3.11+ and Lima 2.2+."""
import argparse
import base64
import getpass
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import shutil
import time

ROOT = Path(__file__).resolve().parents[1]


def environment():
    env = os.environ.copy()
    for key in ("SSH_AUTH_SOCK", "GH_TOKEN", "GITHUB_TOKEN", "OPENAI_API_KEY"):
        env.pop(key, None)
    return env


def run(args, **kwargs):
    return subprocess.run(args, check=True, env=environment(), text=True, **kwargs)


def provision():
    script = (ROOT / "lima/provision.sh").read_text()
    for key, path in {
        "REQUIREMENTS": "config/codex/requirements.toml",
        "CONFIG": "config/codex/config.toml",
        "VERIFY": "scripts/verify_guest.py",
        "APPARMOR": "config/apparmor/agent-vm-bwrap",
        "CHECK_CODEX": "scripts/check_codex.py",
    }.items():
        script = script.replace(f"__{key}_B64__", base64.b64encode((ROOT / path).read_bytes()).decode())
    version = (ROOT / "lima/codex-version").read_text().strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError("codex-version must be an exact release version")
    return script.replace("__CODEX_VERSION__", version)


def render():
    config = json.loads((ROOT / "lima/agent.json").read_text())
    config["provision"] = [{"mode": "system", "script": provision()}]
    return config


def info(name):
    output = run(["limactl", "list", "--json", name], capture_output=True).stdout
    entries = [json.loads(line) for line in output.splitlines() if line.strip()]
    if len(entries) != 1 or entries[0]["name"] != name:
        raise ValueError(f"Expected exactly one VM named {name}")
    return entries[0]


def check_instance(state):
    cfg = state["config"]
    if cfg.get("param", {}).get("agentSandboxConfig") != "v1":
        raise ValueError("Refusing to manage a VM not created by this recipe")
    if not cfg.get("plain") or cfg.get("mounts") or cfg.get("ssh", {}).get("forwardAgent"):
        raise ValueError("Unexpected mounts, forwarding, or non-plain mode; inspect Lima overrides")
    if cfg.get("user", {}).get("name") != "jack":
        raise ValueError("Unexpected administrator account")


def ssh_args(state, user="dev"):
    return ["ssh", "-F", str(Path(state["dir"]) / "ssh.config"),
            "-o", "IdentityAgent=none", "-o", "ForwardAgent=no",
            "-o", "ControlPath=none", "-o", "ControlMaster=no",
            "-l", user, "lima-" + state["name"]]


def remote(state, command, user="dev", **kwargs):
    return run(ssh_args(state, user) + [shlex.join(command)], **kwargs)


def ssh_config(state):
    source = (Path(state["dir"]) / "ssh.config").read_text()
    # Lima emits one Host block; do not silently rewrite arbitrary SSH configuration.
    host_lines = [x for x in source.splitlines() if x.strip().lower().startswith("host ")]
    if len(host_lines) != 1:
        raise ValueError("Unexpected Lima SSH configuration")
    excluded = {"host", "user", "identityagent", "forwardagent", "controlpath", "controlmaster", "controlpersist"}
    body = [x for x in source.splitlines() if x.strip() and not x.lstrip().startswith("#")
            and x.strip().split()[0].lower() not in excluded]
    blocks = []
    for alias, user in ((state["name"], "dev"), (state["name"] + "-admin", "jack")):
        blocks.append(f"Host {alias}\n  User {user}\n  IdentityAgent none\n  ForwardAgent no\n"
                      "  ControlMaster no\n  ControlPath none\n" + "\n".join(body))
    return "\n\n".join(blocks) + "\n"


def install_ssh(state, add_include=False):
    directory = Path.home() / ".ssh/agent-vms"
    target = directory / (state["name"] + ".config")
    if not add_include and not target.exists():
        return
    header = "# Generated by agent-sandbox-config scripts/vm.py\n"
    if target.exists() and not target.read_text().startswith(header):
        raise ValueError(f"Refusing to overwrite unmanaged SSH file: {target}")
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target.write_text(header + ssh_config(state))
    target.chmod(0o600)
    if add_include:
        config = Path.home() / ".ssh/config"
        include = 'Include "~/.ssh/agent-vms/*.config"'
        existing = config.read_text() if config.exists() else ""
        if include not in existing.splitlines():
            if config.is_symlink():
                raise ValueError(f"SSH config is a symlink; add this include to its source: {include}")
            if config.exists():
                shutil.copy2(config, config.with_name(f"config.before-agent-vms-{time.time_ns()}"))
            config.write_text(include + "\n\n" + existing)
            config.chmod(0o600)
        print(f"Installed SSH aliases: {state['name']} (dev), {state['name']}-admin (jack)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["render", "create", "start", "configure", "verify", "shell", "admin", "ssh-config", "install-ssh", "set-token"])
    parser.add_argument("name", nargs="?", default="agent-dev")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,39}", args.name):
        parser.error("VM name must start with a letter and contain only lowercase letters, digits, and hyphens")
    if args.action == "render":
        print(json.dumps(render(), indent=2))
        return
    if args.action == "create":
        # Lima create refuses existing names; never adopt or overwrite an existing VM.
        build = ROOT / ".build"
        build.mkdir(exist_ok=True)
        template = build / "agent.yaml"
        template.write_text(json.dumps(render(), indent=2) + "\n")
        run(["limactl", "validate", str(template)])
        run(["limactl", "create", "--tty=false", "--name=" + args.name, str(template)])
    state = info(args.name)
    check_instance(state)
    if args.action in ("create", "start"):
        run(["limactl", "start", "--tty=false", args.name])
        state = info(args.name)
        check_instance(state)
        remote(state, ["test", "-f", "/usr/local/share/agent-vm/managed"])
        install_ssh(state)
        print(f"Ready. Develop: scripts/vm.py shell {args.name}; administer: scripts/vm.py admin {args.name}")
        return
    if state["status"] != "Running" and args.action != "configure":
        raise ValueError("VM is not running; start it first")
    if args.action == "configure":
        # Persist the new provisioning recipe too, so reboot cannot restore old policy.
        print("Updating provisioning requires a VM restart; active sessions will disconnect.", flush=True)
        if state["status"] == "Running":
            run(["limactl", "stop", args.name])
        expression = ".provision = " + json.dumps(render()["provision"])
        run(["limactl", "edit", "--tty=false", "--set", expression, args.name])
        run(["limactl", "start", "--tty=false", args.name])
        state = info(args.name)
        check_instance(state)
        remote(state, ["test", "-f", "/usr/local/share/agent-vm/managed"])
        install_ssh(state)
    elif args.action == "verify":
        remote(state, ["python3", "/usr/local/share/agent-vm/verify.py"])
    elif args.action in ("shell", "admin"):
        run(ssh_args(state, "jack" if args.action == "admin" else "dev")[:1]
            + ["-t"] + ssh_args(state, "jack" if args.action == "admin" else "dev")[1:])
    elif args.action == "ssh-config":
        print(ssh_config(state), end="")
    elif args.action == "install-ssh":
        install_ssh(state, add_include=True)
    elif args.action == "set-token":
        token = getpass.getpass("Fine-grained GitHub token for this VM (hidden): ")
        if not token or any(c.isspace() for c in token):
            raise ValueError("Expected a nonempty token without whitespace")
        # Token travels only on SSH stdin, never as a command argument or template value.
        remote(state, ["/bin/sh", "-c", "umask 077; mkdir -p ~/.config/agent-vm; "
                       "cat > ~/.config/agent-vm/github-token; chmod 600 ~/.config/agent-vm/github-token"], input=token + "\n")
        print("Token saved for dev. Verify scope against allowed and disallowed PRIVATE repositories.")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        sys.exit(f"{exc.cmd[0]} failed (exit {exc.returncode}); see output above. No local-execution fallback.")
    except ValueError as exc:
        sys.exit(str(exc))
