#!/usr/bin/env ruby
# frozen_string_literal: true

# Host orchestration for this repository's Lima VMs. No third-party gems needed.
require 'base64'
require 'fileutils'
require 'io/console'
require 'json'
require 'open3'
require 'optparse'
require 'shellwords'

class DevelopmentVM
  ROOT = File.expand_path('..', __dir__)
  ACTIONS = %w[render create configure verify ssh-config install-ssh set-token].freeze
  HEADER = "# Generated by agent-sandbox-config scripts/vm.rb\n"
  INCLUDE = 'Include "~/.ssh/agent-vms/*.config"'
  PAYLOADS = {
    'REQUIREMENTS' => 'config/codex/requirements.toml',
    'CONFIG' => 'config/codex/config.toml',
    'DOTFILES' => 'lima/dotfiles.sh',
    'VERIFY' => 'scripts/verify_guest.rb',
    'CHECK_CODEX' => 'scripts/check_codex.rb'
  }.freeze

  def initialize(root: ROOT, home: Dir.home, dotfiles_repo: nil, dotfiles_install: 'install')
    @root = root
    @home = home
    @dotfiles_repo = dotfiles_repo
    @dotfiles_install = dotfiles_install
    if dotfiles_repo && (dotfiles_repo.empty? || dotfiles_repo.start_with?('-'))
      raise 'Expected a dotfiles Git repository URL'
    end
    if dotfiles_install.empty? || dotfiles_install.start_with?('/') || dotfiles_install.split('/').include?('..')
      raise 'Dotfiles installer must be a relative path within the repository'
    end
  end

  def environment
    # nil removes an inherited variable from the child, without changing our ENV.
    %w[SSH_AUTH_SOCK GH_TOKEN GITHUB_TOKEN OPENAI_API_KEY].to_h { |key| [key, nil] }
  end

  def run(args, capture: false, input: nil)
    if capture || !input.nil?
      stdout, stderr, status = Open3.capture3(environment, *args, stdin_data: input || '')
      $stderr.print(stderr)
      $stdout.print(stdout) unless capture
    else
      system(environment, *args)
      status = $?
    end
    unless status&.success?
      raise "#{args.first} failed (exit #{status&.exitstatus}); see output above. No local-execution fallback."
    end
    capture ? stdout : nil
  end

  def provision
    script = File.read(File.join(@root, 'lima/provision.sh'))
    PAYLOADS.each do |key, path|
      script = script.gsub("__#{key}_B64__", Base64.strict_encode64(File.binread(File.join(@root, path))))
    end
    "dotfiles_repository=#{Shellwords.escape(@dotfiles_repo || '')}\n" \
      "dotfiles_install=#{Shellwords.escape(@dotfiles_install)}\n" + script
  end

  def render
    config = JSON.parse(File.read(File.join(@root, 'lima/agent.json')))
    # Setup is sent explicitly over admin SSH, never registered as a boot hook.
    config['provision'] = []
    config
  end

  def info(name)
    output = run(['limactl', 'list', '--json', name], capture: true)
    entries = output.lines.reject { |line| line.strip.empty? }.map { |line| JSON.parse(line) }
    raise "Expected exactly one VM named #{name}" unless entries.length == 1 && entries.first['name'] == name

    entries.first
  end

  def check_instance(state)
    cfg = state.fetch('config')
    unless cfg['plain'] && Array(cfg['mounts']).empty? && !cfg.dig('ssh', 'forwardAgent')
      raise 'Unexpected mounts, forwarding, or non-plain mode; inspect Lima overrides'
    end
    raise 'Boot provisioning is unsupported; create a fresh VM with this recipe' unless Array(cfg['provision']).empty?
    raise 'Unexpected primary account' unless cfg.dig('user', 'name') == 'dev'
  end

  def ssh_args(state, user = 'dev')
    ['ssh', '-F', File.join(state.fetch('dir'), 'ssh.config'),
     '-o', 'IdentityAgent=none', '-o', 'ForwardAgent=no',
     '-o', 'ControlPath=~/.ssh/control-%C', '-o', 'ControlMaster=auto',
     '-o', 'ControlPersist=60',
     '-l', user, "lima-#{state.fetch('name')}"]
  end

  def remote(state, command, user = 'dev', **options)
    # SSH sends a command string to the remote shell, so escape each argument there.
    run(ssh_args(state, user) + [Shellwords.join(command)], **options)
  end

  def ssh_config(state)
    path = File.join(state.fetch('dir'), 'ssh.config').gsub(/[\\"]/) { |char| "\\#{char}" }
    <<~CONFIG
      Host lima-#{state.fetch('name')}
        IdentityAgent none
        ForwardAgent no
        ControlMaster auto
        ControlPath ~/.ssh/control-%C
        ControlPersist 60
        Include "#{path}"

      Host *
    CONFIG
  end

  def install_ssh(state)
    directory = File.join(@home, '.ssh/agent-vms')
    target = File.join(directory, "#{state.fetch('name')}.config")

    if File.exist?(target) && !File.read(target).start_with?(HEADER)
      raise "Refusing to overwrite unmanaged SSH file: #{target}"
    end
    FileUtils.mkdir_p(directory, mode: 0o700)
    File.write(target, HEADER + ssh_config(state))
    File.chmod(0o600, target)

    config = File.join(@home, '.ssh/config')
    existing = File.exist?(config) ? File.read(config) : ''
    unless existing.lines.map(&:chomp).include?(INCLUDE)
      raise "SSH config is a symlink; add this include to its source: #{INCLUDE}" if File.symlink?(config)

      FileUtils.cp(config, "#{config}.before-agent-vms-#{Process.clock_gettime(Process::CLOCK_REALTIME, :nanosecond)}", preserve: true) if File.exist?(config)
      File.write(config, "#{INCLUDE}\n\n#{existing}")
      File.chmod(0o600, config)
    end
    puts "SSH ready: ssh lima-#{state['name']} (dev); ssh root@lima-#{state['name']} (admin)"
  end

  def bootstrap(state)
    remote(state, ['sudo', '-n', '/bin/bash', '-s'], 'dev',
           input: File.read(File.join(@root, 'lima/bootstrap.sh')))
    # Confirm the new administrative route before provisioning removes dev's sudo.
    remote(state, ['test', '-s', '/root/.ssh/authorized_keys'], 'root')
  end

  def configure(state)
    remote(state, ['/bin/bash', '-s'], 'root', input: provision)
    remote(state, ['ruby', '/usr/local/share/agent-vm/verify.rb'])
  end

  def read_token
    console = IO.console
    raise 'A terminal is required to enter a token securely' unless console

    console.getpass('Fine-grained GitHub token for this VM (hidden): ')
  end

  def execute(action, name = 'agent-dev')
    raise "Unknown action: #{action}" unless ACTIONS.include?(action)
    if @dotfiles_repo && !%w[create configure].include?(action)
      raise 'Dotfiles options apply only to create and configure'
    end
    unless /\A[a-z][a-z0-9-]{0,39}\z/.match?(name)
      raise 'VM name must start with a letter and contain only lowercase letters, digits, and hyphens'
    end
    if action == 'render'
      puts JSON.pretty_generate(render)
      return
    end
    if action == 'create'
      # Lima refuses existing names; never adopt or overwrite another VM.
      FileUtils.mkdir_p(File.join(@root, '.build'))
      template = File.join(@root, '.build/agent.yaml')
      File.write(template, JSON.pretty_generate(render) + "\n")
      run(['limactl', 'validate', template])
      run(['limactl', 'create', '--tty=false', "--name=#{name}", template])
    end
    state = info(name)
    check_instance(state)
    if action == 'create'
      run(['limactl', 'start', '--tty=false', name])
      bootstrap(info(name))
      configure(info(name))
      puts "Created and verified. Set up SSH: ruby scripts/vm.rb install-ssh #{name}"
      return
    end
    raise 'VM is not running; start it first' unless state['status'] == 'Running' || action == 'configure'

    case action
    when 'configure'
      run(['limactl', 'start', '--tty=false', name]) unless state['status'] == 'Running'
      configure(info(name))
    when 'verify'
      remote(state, ['ruby', '/usr/local/share/agent-vm/verify.rb'])
    when 'ssh-config'
      print ssh_config(state)
    when 'install-ssh'
      install_ssh(state)
    when 'set-token'
      token = read_token
      raise 'Expected a nonempty token without whitespace' if token.nil? || token.empty? || /\s/.match?(token)

      # Token is sent only on SSH stdin, never in a process argument or recipe.
      remote(state, ['/bin/sh', '-c', 'umask 077; mkdir -p ~/.config/agent-vm; ' \
                                    'cat > ~/.config/agent-vm/github-token; chmod 600 ~/.config/agent-vm/github-token'],
             input: token + "\n")
      puts 'Token saved for dev. Verify scope against allowed and disallowed PRIVATE repositories.'
    end
  end
end

if $PROGRAM_NAME == __FILE__
  dotfiles_options = {}
  parser = OptionParser.new do |options|
    options.banner = "Usage: #{$PROGRAM_NAME} ACTION [NAME]\nActions: #{DevelopmentVM::ACTIONS.join(', ')}\nDefault VM: agent-dev"
    options.on('--dotfiles-repo URL', 'Install this Git repository for root and dev') { |url| dotfiles_options[:dotfiles_repo] = url }
    options.on('--dotfiles-install PATH', 'Executable installer relative to repository (default: install)') { |path| dotfiles_options[:dotfiles_install] = path }
    options.on('-h', '--help', 'Show this help') { puts options; exit }
  end
  begin
    parser.parse!
    raise parser.to_s unless (1..2).cover?(ARGV.length)

    raise '--dotfiles-install requires --dotfiles-repo' if dotfiles_options.key?(:dotfiles_install) && !dotfiles_options.key?(:dotfiles_repo)

    DevelopmentVM.new(**dotfiles_options).execute(*ARGV)
  rescue StandardError => e
    warn e.message
    exit 1
  end
end
