#!/usr/bin/env ruby
# frozen_string_literal: true

# Host orchestration for this repository's Lima VMs. No third-party gems needed.
require 'base64'
require 'fileutils'
require 'io/console'
require 'json'
require 'open3'
require 'optparse'
require 'shellwords'

class DevelopmentVM
  ROOT = File.expand_path('..', __dir__)
  ACTIONS = %w[render create start configure verify shell admin ssh-config install-ssh set-token].freeze
  HEADER = "# Generated by agent-sandbox-config scripts/vm.rb\n"
  OLD_HEADER = "# Generated by agent-sandbox-config scripts/vm.py\n"
  INCLUDE = 'Include "~/.ssh/agent-vms/*.config"'
  PAYLOADS = {
    'REQUIREMENTS' => 'config/codex/requirements.toml',
    'CONFIG' => 'config/codex/config.toml',
    'VERIFY' => 'scripts/verify_guest.rb',
    'APPARMOR' => 'config/apparmor/agent-vm-bwrap',
    'CHECK_CODEX' => 'scripts/check_codex.rb'
  }.freeze

  def initialize(root: ROOT, home: Dir.home)
    @root = root
    @home = home
  end

  def environment
    # nil removes an inherited variable from the child, without changing our ENV.
    %w[SSH_AUTH_SOCK GH_TOKEN GITHUB_TOKEN OPENAI_API_KEY].to_h { |key| [key, nil] }
  end

  def run(args, capture: false, input: nil)
    if capture || !input.nil?
      stdout, stderr, status = Open3.capture3(environment, *args, stdin_data: input || '')
      $stderr.print(stderr)
      $stdout.print(stdout) unless capture
    else
      system(environment, *args)
      status = $?
    end
    unless status&.success?
      raise "#{args.first} failed (exit #{status&.exitstatus}); see output above. No local-execution fallback."
    end
    capture ? stdout : nil
  end

  def provision
    script = File.read(File.join(@root, 'lima/provision.sh'))
    PAYLOADS.each do |key, path|
      script = script.gsub("__#{key}_B64__", Base64.strict_encode64(File.binread(File.join(@root, path))))
    end
    version = File.read(File.join(@root, 'lima/codex-version')).strip
    raise 'codex-version must be an exact release version' unless /\A\d+\.\d+\.\d+\z/.match?(version)

    script.gsub('__CODEX_VERSION__', version)
  end

  def render
    config = JSON.parse(File.read(File.join(@root, 'lima/agent.json')))
    config['provision'] = [{ 'mode' => 'system', 'script' => provision }]
    config
  end

  def info(name)
    output = run(['limactl', 'list', '--json', name], capture: true)
    entries = output.lines.reject { |line| line.strip.empty? }.map { |line| JSON.parse(line) }
    raise "Expected exactly one VM named #{name}" unless entries.length == 1 && entries.first['name'] == name

    entries.first
  end

  def check_instance(state)
    cfg = state.fetch('config')
    unless cfg.dig('param', 'agentSandboxConfig') == 'v1'
      raise 'Refusing to manage a VM not created by this recipe'
    end
    unless cfg['plain'] && Array(cfg['mounts']).empty? && !cfg.dig('ssh', 'forwardAgent')
      raise 'Unexpected mounts, forwarding, or non-plain mode; inspect Lima overrides'
    end
    raise 'Unexpected administrator account' unless cfg.dig('user', 'name') == 'jack'
  end

  def ssh_args(state, user = 'dev')
    ['ssh', '-F', File.join(state.fetch('dir'), 'ssh.config'),
     '-o', 'IdentityAgent=none', '-o', 'ForwardAgent=no',
     '-o', 'ControlPath=none', '-o', 'ControlMaster=no',
     '-l', user, "lima-#{state.fetch('name')}"]
  end

  def remote(state, command, user = 'dev', **options)
    # SSH sends a command string to the remote shell, so escape each argument there.
    run(ssh_args(state, user) + [Shellwords.join(command)], **options)
  end

  def ssh_config(state)
    lines = File.readlines(File.join(state.fetch('dir'), 'ssh.config'), chomp: true)
    raise 'Unexpected Lima SSH configuration' unless lines.count { |line| /\A\s*host\s/i.match?(line) } == 1

    excluded = %w[host user identityagent forwardagent controlpath controlmaster controlpersist]
    body = lines.reject do |line|
      line.strip.empty? || line.lstrip.start_with?('#') || excluded.include?(line.split.first.downcase)
    end
    [[state.fetch('name'), 'dev'], ["#{state.fetch('name')}-admin", 'jack']].map do |name, user|
      "Host #{name}\n  User #{user}\n  IdentityAgent none\n  ForwardAgent no\n" \
        "  ControlMaster no\n  ControlPath none\n#{body.join("\n")}"
    end.join("\n\n") + "\n"
  end

  def install_ssh(state, add_include: false)
    directory = File.join(@home, '.ssh/agent-vms')
    target = File.join(directory, "#{state.fetch('name')}.config")
    return unless add_include || File.exist?(target)

    if File.exist?(target) && !File.read(target).start_with?(HEADER, OLD_HEADER)
      raise "Refusing to overwrite unmanaged SSH file: #{target}"
    end
    FileUtils.mkdir_p(directory, mode: 0o700)
    File.write(target, HEADER + ssh_config(state))
    File.chmod(0o600, target)
    return unless add_include

    config = File.join(@home, '.ssh/config')
    existing = File.exist?(config) ? File.read(config) : ''
    unless existing.lines.map(&:chomp).include?(INCLUDE)
      raise "SSH config is a symlink; add this include to its source: #{INCLUDE}" if File.symlink?(config)

      FileUtils.cp(config, "#{config}.before-agent-vms-#{Process.clock_gettime(Process::CLOCK_REALTIME, :nanosecond)}", preserve: true) if File.exist?(config)
      File.write(config, "#{INCLUDE}\n\n#{existing}")
      File.chmod(0o600, config)
    end
    puts "Installed SSH aliases: #{state['name']} (dev), #{state['name']}-admin (jack)"
  end

  def ready(name)
    state = info(name)
    check_instance(state)
    remote(state, ['test', '-f', '/usr/local/share/agent-vm/managed'])
    install_ssh(state)
  end

  def read_token
    console = IO.console
    raise 'A terminal is required to enter a token securely' unless console

    console.getpass('Fine-grained GitHub token for this VM (hidden): ')
  end

  def execute(action, name = 'agent-dev')
    raise "Unknown action: #{action}" unless ACTIONS.include?(action)
    unless /\A[a-z][a-z0-9-]{0,39}\z/.match?(name)
      raise 'VM name must start with a letter and contain only lowercase letters, digits, and hyphens'
    end
    if action == 'render'
      puts JSON.pretty_generate(render)
      return
    end
    if action == 'create'
      # Lima refuses existing names; never adopt or overwrite another VM.
      FileUtils.mkdir_p(File.join(@root, '.build'))
      template = File.join(@root, '.build/agent.yaml')
      File.write(template, JSON.pretty_generate(render) + "\n")
      run(['limactl', 'validate', template])
      run(['limactl', 'create', '--tty=false', "--name=#{name}", template])
    end
    state = info(name)
    check_instance(state)
    if %w[create start].include?(action)
      run(['limactl', 'start', '--tty=false', name])
      ready(name)
      puts "Ready. Develop: scripts/vm.rb shell #{name}; administer: scripts/vm.rb admin #{name}"
      return
    end
    raise 'VM is not running; start it first' unless state['status'] == 'Running' || action == 'configure'

    case action
    when 'configure'
      puts 'Updating provisioning requires a VM restart; active sessions will disconnect.'
      $stdout.flush
      run(['limactl', 'stop', name]) if state['status'] == 'Running'
      # Persist the recipe so a reboot cannot restore the old provisioning.
      expression = '.provision = ' + JSON.generate(render.fetch('provision'))
      run(['limactl', 'edit', '--tty=false', '--set', expression, name])
      run(['limactl', 'start', '--tty=false', name])
      ready(name)
    when 'verify'
      remote(state, ['ruby', '/usr/local/share/agent-vm/verify.rb'])
    when 'shell', 'admin'
      run(ssh_args(state, action == 'admin' ? 'jack' : 'dev').insert(1, '-t'))
    when 'ssh-config'
      print ssh_config(state)
    when 'install-ssh'
      install_ssh(state, add_include: true)
    when 'set-token'
      token = read_token
      raise 'Expected a nonempty token without whitespace' if token.nil? || token.empty? || /\s/.match?(token)

      # Token is sent only on SSH stdin, never in a process argument or recipe.
      remote(state, ['/bin/sh', '-c', 'umask 077; mkdir -p ~/.config/agent-vm; ' \
                                    'cat > ~/.config/agent-vm/github-token; chmod 600 ~/.config/agent-vm/github-token'],
             input: token + "\n")
      puts 'Token saved for dev. Verify scope against allowed and disallowed PRIVATE repositories.'
    end
  end
end

if $PROGRAM_NAME == __FILE__
  parser = OptionParser.new do |options|
    options.banner = "Usage: #{$PROGRAM_NAME} ACTION [NAME]\nActions: #{DevelopmentVM::ACTIONS.join(', ')}\nDefault VM: agent-dev"
    options.on('-h', '--help', 'Show this help') { puts options; exit }
  end
  begin
    parser.parse!
    raise parser.to_s unless (1..2).cover?(ARGV.length)

    DevelopmentVM.new.execute(*ARGV)
  rescue StandardError => e
    warn e.message
    exit 1
  end
end
